### ISSUE TITLE
Model checkpoint is down

### ISSUE THREAD

**Issue by HippocampusGirl** [ngohgia/text2brain#5]
The weights linked in the readme at <https://drive.google.com/file/d/1IwUGtdbmseTrFU9NAA9gC-k-Iy5hesQs/view?usp=sharing> seem to be offline.

![image](https://github.com/ngohgia/text2brain/assets/789054/0911a529-d5fe-4c05-9433-ea887815fed0)

**Comment by ngohgia** [comment]
sorry about that, looks like the file was removed by mistake. I have reuploaded the checkpoint. Thanks!

**Comment by HippocampusGirl** [comment]
Thank you very much!
